/** Spiegazioni dei controlli della sidebar destra: cosa sono e cosa fanno. Mostrate come tooltip. */
export const TIPS = {
  posX: 'Posizione X: sposta l\'oggetto a sinistra (valori negativi) o a destra (positivi) sul piatto, in mm. 0 è il centro del piatto.',
  posY: 'Posizione Y: sposta l\'oggetto verso il fronte (valori negativi) o verso il retro (positivi) del piatto, in mm.',
  posZ: 'Posizione Z: altezza del centro dell\'oggetto rispetto al piatto, in mm. Per appoggiarlo sul piatto usa il tasto B.',
  rotX: 'Rotazione X: ruota l\'oggetto attorno all\'asse X (da sinistra a destra), in gradi. Si applica prima di Y e Z.',
  rotY: 'Rotazione Y: ruota l\'oggetto attorno all\'asse Y (dal fronte al retro), in gradi.',
  rotZ: 'Rotazione Z: fa girare l\'oggetto su se stesso, come sul piatto di un giradischi, in gradi.',

  boxSizeX: 'Larghezza: dimensione del cubo lungo X, in mm.',
  boxSizeY: 'Profondità: dimensione del cubo lungo Y, in mm.',
  boxSizeZ: 'Altezza: dimensione del cubo lungo Z, in mm.',
  rounding: 'Raccordo: raggio con cui si arrotondano spigoli e angoli, in mm. 0 lascia gli spigoli vivi. Il massimo dipende dalla forma.',
  radius: 'Raggio: distanza dal centro al bordo della forma, in mm. Il diametro è il doppio.',
  radiusX: 'Raggio X: raggio della forma lungo l\'asse X, in mm. Finché non tocchi Raggio Y la forma resta tonda e i due raggi si muovono insieme.',
  radiusY: 'Raggio Y: raggio lungo l\'asse Y, in mm. Un valore diverso da Raggio X rende la forma ovale (ellisse) invece che tonda.',
  radiusZ: 'Raggio Z: raggio in altezza, in mm. Diverso da Raggio X e Y trasforma la sfera in un ellissoide (uovo, disco).',
  radiusYCone: 'Raggio Y: raggio lungo Y dell\'estremità più larga del cono, in mm. L\'altra estremità mantiene lo stesso rapporto.',
  radiusBottom: 'Raggio inferiore: raggio della base del cono, in mm.',
  radiusTop: 'Raggio superiore: raggio della cima del cono, in mm. A 0 diventa una punta.',
  height: 'Altezza: quanto la forma è alta lungo Z, in mm.',
  majorRadius: 'Raggio del toro: distanza dal centro del toro al centro del suo tubo, in mm.',
  minorRadius: 'Raggio del tubo: spessore del tubo del toro, in mm.',
  polySize: 'Dimensione: distanza tra due facce opposte, in mm. È la misura che si usa per i dadi.',

  width: 'Larghezza: dimensione del profilo 2D lungo X, in mm.',
  depth: 'Profondità: dimensione del profilo 2D lungo Y, in mm.',
  profileWidth: 'Larghezza: ingombro della sezione del profilato lungo X, in mm.',
  profileDepth: 'Profondità: ingombro della sezione del profilato lungo Y, in mm.',
  rootRadius: "Raccordo interno: raggio con cui si arrotonda l'angolo tra ala e anima, come nei profilati laminati, in mm. 0 lascia lo spigolo vivo.",
  tubeWall: 'Parete: spessore della parete del tubolare, in mm. Il foro interno è quello che resta.',
  tubeCorner: 'Raccordo angoli: raggio degli angoli esterni del tubolare, in mm. 0 lascia gli angoli vivi; quelli interni seguono con il raggio ridotto della parete.',
  tubeRadius: 'Raggio: raggio esterno del tubolare tondo, in mm. Il diametro è il doppio.',
  profileLength: 'Lunghezza: quanto è lungo il profilato lungo Z, in mm. Per sdraiarlo sul piatto ruotalo di 90° su X o Y.',
  ratioLocked: 'Proporzioni bloccate: le misure e la maniglia Ridimensiona cambiano insieme, la forma non si deforma. Clic per sbloccare.',
  ratioUnlocked: 'Proporzioni libere: ogni misura si cambia da sola (la forma si deforma). Clic per bloccare.',
  scale: 'Scala: dimensione della forma rispetto a quella iniziale (per gli SVG, a quella del file), in %. Ridimensiona sempre in proporzione.',
  offset: 'Contorno: ingrandisce (valori positivi) o restringe (negativi) il profilo 2D di questi mm prima di estruderlo, come offset() di OpenSCAD. Utile per ispessire un testo o dare gioco a un incastro.',
  offsetJoin: 'Angoli del contorno: arrotondati (offset con r) oppure vivi (offset con delta, gli angoli restano a spigolo).',
  extrusionKind: "Tipo di estrusione: Lineare estrude il profilo in altezza; Rotazionale lo fa girare attorno all'asse Z (come rotate_extrude di OpenSCAD) per anelli, tori, vasi e archi.",
  revolveAngle: 'Angolo: di quanti gradi gira il profilo, da +X in senso antiorario. 360 è il giro completo, meno gradi danno un arco aperto.',
  revolveRadius: "Raggio: distanza del centro del profilo dall'asse di rotazione, in mm. La parte del profilo oltre l'asse viene tagliata.",
  revolveSegments: 'Segmenti: in quanti passi si divide il giro intero (come $fn di OpenSCAD): più segmenti, superficie più liscia.',
  extrudeHeight: 'Altezza dell\'estrusione: quanto il profilo 2D cresce verso l\'alto, in mm.',
  twist: 'Torsione: di quanti gradi la cima dell\'estrusione ruota rispetto alla base, per ottenere forme a spirale.',
  text: 'Testo: le lettere da estrudere. Si conferma con Invio o uscendo dal campo (Esc annulla).',
  font: 'Font: lo stile delle lettere. I file dei font stanno nello ZIP dell\'export OpenSCAD.',
  textSize: 'Dimensione: altezza approssimativa delle maiuscole, in mm (come size di text() in OpenSCAD).',
  textSpacing: 'Spaziatura: moltiplica la distanza tra le lettere (1 = normale, come spacing di text() in OpenSCAD).',
  scaleTop: 'Scala cima: dimensione della cima rispetto alla base, in %. 100 dà un prisma, 0 una punta (cono o piramide).',
  segments: 'Segmenti: quanti lati ha la curva. Pochi lati danno un poligono, molti lati una forma liscia ma più pesante da calcolare.',
  sides: 'Lati: numero di lati del poligono. 3 è un triangolo, 6 un esagono, 12 un dodecagono.',
} as const;
