// Catalogo dei simboli della libreria. Ogni simbolo sta nel font indicato (src/scene/symbolCatalog.test.ts lo verifica:
// se un carattere non ha il glifo nel suo font il test fallisce, quindi nessun simbolo può uscire vuoto).

/** Un simbolo Unicode: il carattere, il nome in italiano e il font del catalogo (fontCatalog.ts) che lo contiene. */
export interface SymbolInfo {
  char: string;
  name: string;
  font: string;
}

export interface SymbolGroup {
  title: string;
  symbols: SymbolInfo[];
}

export const SYMBOL_GROUPS: SymbolGroup[] = [
  {
    title: 'Frecce',
    symbols: [
      { char: '←', name: 'Freccia a sinistra', font: 'noto-symbols' },
      { char: '→', name: 'Freccia a destra', font: 'noto-symbols' },
      { char: '↑', name: 'Freccia in su', font: 'noto-symbols' },
      { char: '↓', name: 'Freccia in giù', font: 'noto-symbols' },
      { char: '↔', name: 'Freccia doppia orizzontale', font: 'noto-symbols' },
      { char: '↕', name: 'Freccia doppia verticale', font: 'noto-symbols' },
      { char: '↖', name: 'Freccia in alto a sinistra', font: 'noto-symbols' },
      { char: '↗', name: 'Freccia in alto a destra', font: 'noto-symbols' },
      { char: '↘', name: 'Freccia in basso a destra', font: 'noto-symbols' },
      { char: '↙', name: 'Freccia in basso a sinistra', font: 'noto-symbols' },
      { char: '⇐', name: 'Freccia doppia a sinistra', font: 'noto-math' },
      { char: '⇒', name: 'Freccia doppia a destra', font: 'noto-math' },
      { char: '⇑', name: 'Freccia doppia in su', font: 'noto-math' },
      { char: '⇓', name: 'Freccia doppia in giù', font: 'noto-math' },
      { char: '⇔', name: 'Freccia doppia bidirezionale', font: 'noto-math' },
      { char: '↺', name: 'Rotazione antioraria', font: 'noto-math' },
      { char: '↻', name: 'Rotazione oraria', font: 'noto-math' },
      { char: '➔', name: 'Freccia piena', font: 'noto-symbols-2' },
      { char: '➜', name: 'Freccia pesante', font: 'noto-symbols-2' },
      { char: '➤', name: 'Punta di freccia', font: 'noto-symbols-2' },
      { char: '➥', name: 'Freccia curva', font: 'noto-symbols-2' },
    ],
  },
  {
    title: 'Stelle e forme',
    symbols: [
      { char: '★', name: 'Stella piena', font: 'noto-symbols-2' },
      { char: '☆', name: 'Stella vuota', font: 'noto-symbols-2' },
      { char: '✦', name: 'Stella a quattro punte', font: 'noto-symbols-2' },
      { char: '✧', name: 'Stella a quattro punte vuota', font: 'noto-symbols-2' },
      { char: '✩', name: 'Stella cerchiata', font: 'noto-symbols-2' },
      { char: '✪', name: 'Stella in cerchio', font: 'noto-symbols-2' },
      { char: '✫', name: 'Stella aperta', font: 'noto-symbols-2' },
      { char: '✬', name: 'Stella nera in cerchio', font: 'noto-symbols-2' },
      { char: '✯', name: 'Stella a punte', font: 'noto-symbols-2' },
      { char: '●', name: 'Cerchio pieno', font: 'noto-symbols-2' },
      { char: '○', name: 'Cerchio vuoto', font: 'noto-symbols-2' },
      { char: '◆', name: 'Rombo pieno', font: 'noto-symbols-2' },
      { char: '◇', name: 'Rombo vuoto', font: 'noto-symbols-2' },
      { char: '■', name: 'Quadrato pieno', font: 'noto-symbols-2' },
      { char: '□', name: 'Quadrato vuoto', font: 'noto-symbols-2' },
      { char: '▲', name: 'Triangolo in su', font: 'noto-symbols-2' },
      { char: '△', name: 'Triangolo in su vuoto', font: 'noto-symbols-2' },
      { char: '▼', name: 'Triangolo in giù', font: 'noto-symbols-2' },
      { char: '▽', name: 'Triangolo in giù vuoto', font: 'noto-symbols-2' },
      { char: '◀', name: 'Triangolo a sinistra', font: 'noto-symbols-2' },
      { char: '▶', name: 'Triangolo a destra', font: 'noto-symbols-2' },
      { char: '✚', name: 'Croce greca', font: 'noto-symbols-2' },
      { char: '✖', name: 'Croce di moltiplicazione', font: 'noto-symbols-2' },
      { char: '✱', name: 'Asterisco pesante', font: 'noto-symbols-2' },
      { char: '✲', name: 'Asterisco a cerchio', font: 'noto-symbols-2' },
      { char: '❖', name: 'Rombo a quattro rombi', font: 'noto-symbols-2' },
      { char: '✿', name: 'Fiore', font: 'noto-symbols-2' },
      { char: '❀', name: 'Fiore a petali', font: 'noto-symbols-2' },
      { char: '❁', name: 'Fiore ad otto petali', font: 'noto-symbols-2' },
      { char: '❂', name: 'Sole', font: 'noto-symbols-2' },
      { char: '❄', name: 'Fiocco di neve', font: 'noto-symbols-2' },
      { char: '❅', name: 'Fiocco di neve stretto', font: 'noto-symbols-2' },
      { char: '❆', name: 'Fiocco di neve pesante', font: 'noto-symbols-2' },
    ],
  },
  {
    title: 'Cuori e carte',
    symbols: [
      { char: '♥', name: 'Cuore', font: 'noto-symbols-2' },
      { char: '♡', name: 'Cuore vuoto', font: 'noto-symbols-2' },
      { char: '♠', name: 'Picche', font: 'noto-symbols-2' },
      { char: '♣', name: 'Fiori', font: 'noto-symbols-2' },
      { char: '♦', name: 'Quadri', font: 'noto-symbols-2' },
      { char: '♤', name: 'Picche vuote', font: 'noto-symbols-2' },
      { char: '♧', name: 'Fiori vuoti', font: 'noto-symbols-2' },
      { char: '♢', name: 'Quadri vuoti', font: 'noto-symbols-2' },
      { char: '❤', name: 'Cuore pesante', font: 'noto-symbols-2' },
      { char: '❥', name: 'Cuore rotante', font: 'noto-symbols-2' },
      { char: '❣', name: 'Cuore con punto esclamativo', font: 'noto-symbols-2' },
      { char: '❦', name: 'Foglia fiorita', font: 'noto-symbols-2' },
      { char: '❧', name: 'Foglia rotante', font: 'noto-symbols-2' },
      { char: '☙', name: 'Foglia', font: 'noto-symbols-2' },
    ],
  },
  {
    title: 'Segni e simboli',
    symbols: [
      { char: '✓', name: 'Spunta', font: 'noto-symbols-2' },
      { char: '✔', name: 'Spunta pesante', font: 'noto-symbols-2' },
      { char: '✗', name: 'Croce', font: 'noto-symbols-2' },
      { char: '✘', name: 'Croce pesante', font: 'noto-symbols-2' },
      { char: '✕', name: 'Moltiplicazione', font: 'noto-symbols-2' },
      { char: '✜', name: 'Croce aperta', font: 'noto-symbols-2' },
      { char: '☑', name: 'Casella spuntata', font: 'noto-symbols-2' },
      { char: '☒', name: 'Casella con croce', font: 'noto-symbols-2' },
      { char: '⚠', name: 'Attenzione', font: 'noto-symbols-2' },
      { char: '☠', name: 'Teschio', font: 'noto-symbols-2' },
      { char: '☢', name: 'Radioattività', font: 'noto-symbols-2' },
      { char: '☣', name: 'Rischio biologico', font: 'noto-symbols-2' },
      { char: '☮', name: 'Pace', font: 'noto-symbols' },
      { char: '☯', name: 'Yin e yang', font: 'noto-symbols' },
      { char: '☸', name: 'Ruota del dharma', font: 'noto-symbols' },
      { char: '♻', name: 'Riciclo', font: 'noto-symbols' },
      { char: '⚛', name: 'Atomo', font: 'noto-symbols' },
      { char: '✝', name: 'Croce latina', font: 'noto-symbols' },
      { char: '✡', name: 'Stella di David', font: 'noto-symbols' },
      { char: '☪', name: 'Mezzaluna e stella', font: 'noto-symbols' },
      { char: '☬', name: 'Khanda', font: 'noto-symbols' },
      { char: '☭', name: 'Falce e martello', font: 'noto-symbols' },
      { char: '⛔', name: 'Divieto di accesso', font: 'noto-symbols-2' },
      { char: '♿', name: 'Accessibilità', font: 'noto-symbols-2' },
    ],
  },
  {
    title: 'Meteo e musica',
    symbols: [
      { char: '☀', name: 'Sole', font: 'noto-symbols-2' },
      { char: '☼', name: 'Sole con raggi', font: 'noto-symbols-2' },
      { char: '☁', name: 'Nuvola', font: 'noto-symbols-2' },
      { char: '☂', name: 'Ombrello', font: 'noto-symbols-2' },
      { char: '☃', name: 'Pupazzo di neve', font: 'noto-symbols-2' },
      { char: '☄', name: 'Cometa', font: 'noto-symbols-2' },
      { char: '⚡', name: 'Fulmine', font: 'noto-symbols-2' },
      { char: '☾', name: 'Luna crescente', font: 'noto-symbols' },
      { char: '☽', name: 'Luna calante', font: 'noto-symbols' },
      { char: '♩', name: 'Semiminima', font: 'noto-symbols' },
      { char: '♪', name: 'Croma', font: 'noto-symbols' },
      { char: '♫', name: 'Crome legate', font: 'noto-symbols' },
      { char: '♬', name: 'Semicrome legate', font: 'noto-symbols' },
      { char: '♭', name: 'Bemolle', font: 'noto-symbols' },
      { char: '♮', name: 'Bequadro', font: 'noto-symbols' },
      { char: '♯', name: 'Diesis', font: 'noto-symbols' },
    ],
  },
  {
    title: 'Matematica e lettere',
    symbols: [
      { char: '∞', name: 'Infinito', font: 'noto-math' },
      { char: '≈', name: 'Circa uguale', font: 'noto-math' },
      { char: '≠', name: 'Diverso', font: 'noto-math' },
      { char: '≤', name: 'Minore o uguale', font: 'noto-math' },
      { char: '≥', name: 'Maggiore o uguale', font: 'noto-math' },
      { char: '±', name: 'Più o meno', font: 'noto-math' },
      { char: '×', name: 'Per', font: 'noto-symbols-2' },
      { char: '÷', name: 'Diviso', font: 'noto-symbols-2' },
      { char: '√', name: 'Radice quadrata', font: 'noto-math' },
      { char: '∑', name: 'Sommatoria', font: 'noto-math' },
      { char: '∏', name: 'Produttoria', font: 'noto-math' },
      { char: '∫', name: 'Integrale', font: 'noto-math' },
      { char: '∂', name: 'Derivata parziale', font: 'noto-math' },
      { char: '∆', name: 'Incremento', font: 'noto-math' },
      { char: '∇', name: 'Nabla', font: 'noto-math' },
      { char: '∈', name: 'Appartiene', font: 'noto-math' },
      { char: '∉', name: 'Non appartiene', font: 'noto-math' },
      { char: '∩', name: 'Intersezione', font: 'noto-math' },
      { char: '∪', name: 'Unione', font: 'noto-math' },
      { char: '⊂', name: 'Sottoinsieme', font: 'noto-math' },
      { char: '⊃', name: 'Sovrainsieme', font: 'noto-math' },
      { char: '⊕', name: 'Somma diretta', font: 'noto-math' },
      { char: '⊗', name: 'Prodotto tensoriale', font: 'noto-math' },
      { char: 'π', name: 'Pi greco', font: 'noto-math' },
      { char: 'Ω', name: 'Omega', font: 'noto-math' },
      { char: 'μ', name: 'Mu', font: 'noto-math' },
      { char: 'α', name: 'Alfa', font: 'noto-math' },
      { char: 'β', name: 'Beta', font: 'noto-math' },
      { char: 'γ', name: 'Gamma', font: 'noto-math' },
      { char: 'δ', name: 'Delta', font: 'noto-math' },
      { char: 'θ', name: 'Theta', font: 'noto-math' },
      { char: 'λ', name: 'Lambda', font: 'noto-math' },
    ],
  },
  {
    title: 'Oggetti e varie',
    symbols: [
      { char: '✂', name: 'Forbici', font: 'noto-symbols-2' },
      { char: '✈', name: 'Aereo', font: 'noto-symbols-2' },
      { char: '✉', name: 'Busta', font: 'noto-symbols-2' },
      { char: '☎', name: 'Telefono', font: 'noto-symbols-2' },
      { char: '✆', name: 'Telefono in cerchio', font: 'noto-symbols-2' },
      { char: '⌘', name: 'Tasto comando', font: 'noto-symbols-2' },
      { char: '⌥', name: 'Tasto opzione', font: 'noto-symbols-2' },
      { char: '⏎', name: 'Invio', font: 'noto-symbols-2' },
      { char: '⚙', name: 'Ingranaggio', font: 'noto-symbols' },
      { char: '⚑', name: 'Bandiera', font: 'noto-symbols' },
      { char: '⚐', name: 'Bandiera vuota', font: 'noto-symbols' },
      { char: '✎', name: 'Matita', font: 'noto-symbols-2' },
      { char: '✏', name: 'Matita pesante', font: 'noto-symbols-2' },
      { char: '☺', name: 'Faccia sorridente', font: 'noto-symbols' },
      { char: '☻', name: 'Faccia sorridente piena', font: 'noto-symbols' },
      { char: '☹', name: 'Faccia triste', font: 'noto-symbols' },
      { char: '♀', name: 'Femmina', font: 'noto-symbols' },
      { char: '♂', name: 'Maschio', font: 'noto-symbols' },
      { char: '†', name: 'Croce tipografica', font: 'noto-math' },
      { char: '‡', name: 'Doppia croce tipografica', font: 'noto-math' },
      { char: '™', name: 'Marchio', font: 'noto-symbols-2' },
      { char: '©', name: 'Copyright', font: 'noto-symbols-2' },
      { char: '®', name: 'Marchio registrato', font: 'noto-symbols-2' },
      { char: '§', name: 'Paragrafo', font: 'noto-symbols-2' },
      { char: '¶', name: 'Capoverso', font: 'noto-symbols-2' },
      { char: '°', name: 'Gradi', font: 'noto-symbols-2' },
    ],
  },
];

/** Tutti i simboli, in ordine di gruppo. */
export const SYMBOLS: SymbolInfo[] = SYMBOL_GROUPS.flatMap((g) => g.symbols);
